# OPENAI_BASE_PATH: v1/chat/completions
# GOOSE_PROVIDER: openai
# OPENAI_HOST:
extensions:
    "@executeautomation/playwright-mcp-server":
        args:
            - -y
            - "@executeautomation/playwright-mcp-server"
        bundled: null
        cmd: npx
        description: null
        enabled: true
        env_keys: []
        envs: {}
        name: "@executeautomation/playwright-mcp-server"
        timeout: 300
        type: stdio
    "@modelcontextprotocol/server-memory":
        args:
            - -y
            - "@modelcontextprotocol/server-memory"
        bundled: null
        cmd: npx
        description: null
        enabled: true
        env_keys: []
        envs: {}
        name: "@modelcontextprotocol/server-memory"
        timeout: 300
        type: stdio
    "@modelcontextprotocol/server-sequential-thinking":
        args:
            - -y
            - "@modelcontextprotocol/server-sequential-thinking"
        bundled: null
        cmd: npx
        description: null
        enabled: true
        env_keys: []
        envs: {}
        name: "@modelcontextprotocol/server-sequential-thinking"
        timeout: 300
        type: stdio
    computercontroller:
        bundled: true
        display_name: Computer Controller
        enabled: false
        name: computercontroller
        timeout: 300
        type: builtin
    developer:
        bundled: true
        display_name: Developer
        enabled: true
        name: developer
        timeout: 300
        type: builtin
    ddg-mcp:
        args:
        - ddg-mcp
        bundled: null
        cmd: uvx
        description: null
        enabled: true
        env_keys: []
        envs: {}
        name: ddg-mcp
        timeout: 300
        type: stdio
    # duckduckgo-mcp-server:
    #     args:
    #         - duckduckgo-mcp-server
    #     bundled: null
    #     cmd: uvx
    #     description: null
    #     enabled: true
    #     env_keys: []
    #     envs: {}
    #     name: duckduckgo-mcp-server
    #     timeout: 300
    #     type: stdio
    memory:
        bundled: true
        display_name: Memory
        enabled: true
        name: memory
        timeout: 300
        type: builtin
    speech-mcp:
        args:
            - speech-mcp
        bundled: null
        cmd: uvx
        description: null
        enabled: true
        env_keys: []
        envs: {}
        name: speech-mcp
        timeout: 300
        type: stdio
    kit:
        args:
        - run
        - --python
        - '3.11'
        - --with
        - cased-kit
        - python
        - -m
        - kit.mcp
        bundled: null
        cmd: uv
        description: null
        enabled: true
        env_keys: []
        envs: {}
        name: kit
        timeout: 300
        type: stdio
    mcp-deepwiki:
        args:
            - -y
            - mcp-deepwiki@latest
        bundled: null
        cmd: npx
        description: null
        enabled: true
        env_keys: []
        envs: {}
        name: mcp-deepwiki
        timeout: 300
        type: stdio
# GOOSE_MODEL: deepseek-v3-0324
GOOSE_MODE: smart_approve
