ruleDirs: ["./rules"]
customLanguages:
  forester:
      libraryPath: ../helix/runtime/grammars/forester.so     # path to dynamic library
      extensions: [tree]           # file extensions for this language
      # expandoChar: _               # optional char to replace $ in your pattern
