# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: openai
# model: !ENV 'openai/${OPENAI_API_MODEL}'
rag_embedding_model: om:bge-m3
rag_chunk_size: 1500
rag_chunk_overlap: 75

clients:
    - type: openai-compatible
      name: openai
      api_base: !ENV ${OPENAI_API_BASE}
      api_key: !ENV ${OPENAI_API_KEY}
      models:
          - name: !ENV ${OPENAI_API_MODEL}
            max_input_tokens: null
    # - type: openai-compatible
    #   name: om
    #   api_base: http://127.0.0.1:11434/v1/
    #   # api_auth: null
    #   models:
    #       - name: bge-m3
    #         type: embedding
    #         default_chunk_size: 1500
    #         max_batch_size: 100
    # - type: openai-compatible
    #   name: mini
    #   api_base: !ENV ${MINI_API_BASE}
    #   models:
    #       - name: lms:deepseek-r1-distill-qwen-32b
    #       - name: lms:deepseek-r1-distill-llama-70b
    #       - name: lms:fuseo1-deepseekr1-qwq-skyt1-flash-32b-preview
    #       - name: lms:qwq-32b
