layouts:
    - bsp
    - wide

# # First mod (default option + shift).
# mod1:
#   - option
#   - shift
#   # - control
#   # - command

# # Second mod (default option + shift + control).
# mod2:
#   - option
#   - shift
#   - control
#   # - command

# Automatically quit and reopen Amethyst.
relaunch-amethyst:
  mod: mod1
  key: z

# focus-follows-mouse: true

# screen-padding-top: 10
enables-layout-hud: false
enables-layout-hud-on-space-change: false

