[forest]
trees = ["trees"]
assets = ["assets"]
prefixes = ["uts", "ag", "tt", "ca", "spin", "hopf"]
theme = "theme"
root = "index"
base_url = "https://utensil.github.io/forest/"
stylesheet = "uts-forest.xsl"
