#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""Import the reviewed post-September-2025 Raindrop clips into weekly trees.

Only ``cog-land/clips/raindrops`` is an input.  Existing Raindrop tags are
preserved.  The small mapping below is the source-text-only review of the
otherwise empty-tag clips; it introduces no new tag vocabulary.
"""

from __future__ import annotations

import argparse
import ast
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit


AFTER = "2025-09-30"
EXPECTED_SOURCE = 436
EXPECTED_BASELINE_EXCLUSIONS = 3
EXPECTED_OUTPUT = 433
MAX_DAILY = 15
MIN_DAILY = 10
ROOT_TREE = Path("trees/uts-0018.tree")
TREES_DIR = Path("trees")
ROOT_2025 = "\\subtree[2025]{"
ROOT_2025_TITLE = "\n\\title{Year 2025}\n\n"
ROOT_2025_BASELINE_MONTH = "\\subtree[2025-10]{"
GENERATED_MARKER = "% Raindrop-only intake generated by import_raindrop_links.py"

# Reviewed by Luna Max from local title/body text only.  The stale-bot entry is
# intentionally present in the audit source but excluded before this mapping is
# needed because its URL is already in Forest.
EMPTY_TAGS = {
    "hunt/2026-07-10-my-thoughts-on-the-bun-rust-rewrite.md": ("rust", "zig", "bun"),
    "hunt/2026-07-10-rewriting-bun-in-rust.md": ("rust", "zig", "bun", "benchmark", "perf"),
    "hunt/2026-07-13-vim-of-coding-agents-rasyidan-a-f.md": ("agent", "tui", "nvim", "workflow"),
    "hunt/2026-07-17-benchmarks-are-dead-for-us.md": ("agent", "benchmark", "perf"),
    "hunt/2026-07-18-a-visual-guide-to-attention-variants-in-modern-llms.md": ("lm", "disect"),
    "hunt/2026-07-18-lets-talk-about-encrypted-reasoning.md": ("sec", "crypto", "agent"),
    "hunt/2026-07-18-richard-sutton-on-oak-at-rlc-2025.md": ("agent/idea",),
    "hunt/2026-07-19-dreaming-better-memory-for-a-more-helpful-chatgpt.md": ("agent", "context"),
    "hunt/2026-07-21-human-mathematicians-are-being-outcounterexampled.md": ("math", "counterexample", "jacobian-conjecture"),
    "hunt/2026-07-21-jacobian-conjecture-counterexample-verification.md": ("math", "jacobian-conjecture", "counterexample", "formal"),
    "hunt/2026-07-21-language-model-harnesses-are-compositional-generalizers.md": ("agent", "lm", "context"),
    "hunt/2026-07-21-the-new-counterexample-to-the-jacobian-conjecture.md": ("math", "jacobian-conjecture", "counterexample"),
    "hunt/2026-07-22-a-digestion-of-the-jacobian-conjecture-counterexample.md": ("math", "jacobian-conjecture", "counterexample"),
    "hunt/2026-07-22-counterexample-to-the-jacobian-conjecture.md": ("math", "jacobian-conjecture", "counterexample", "formal"),
    "hunt/2026-07-22-jacobian-conjecture-counterexample.md": ("math", "jacobian-conjecture", "counterexample", "chatgpt"),
    "hunt/2026-07-30-counterexample-discovery-method.md": ("agent/idea", "math", "counterexample"),
    "rss/2025-10-17-hacker-news-the-good-parts.md": ("news", "web"),
    "rss/2025-10-17-hyperflask.md": ("py", "web"),
    "rss/2025-10-21-x86-64-playground.md": ("asm", "debugger", "sandbox", "web"),
    "rss/2025-10-28-json-query-a-small-flexible-and-expandable-json-query-language.md": ("json", "lang", "data-org"),
    "rss/2025-11-24-applepico-banana-400k.md": ("ml", "model-edit", "paper"),
    "rss/2026-01-14-finbarryolobox-let-your-ai-go-full-send-your-home-directory-stays-home.md": ("agent", "sandbox", "sec"),
    "rss/2026-01-30-introducing-moltworker-a-self-hosted-personal-ai-agent-minus-the-minis.md": ("agent", "sandbox", "selfhost"),
}


@dataclass(frozen=True)
class Link:
    path: str
    url: str
    title: str
    source_date: str
    tags: tuple[str, ...]


def frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not match:
        raise ValueError(f"clip lacks frontmatter: {path}")
    values: dict[str, str] = {}
    for line in match.group(1).splitlines():
        key, separator, value = line.partition(":")
        if separator and not line.startswith((" ", "-")):
            values[key] = value.strip()
    return values


def parse_tags(value: str) -> tuple[str, ...]:
    if value == "[]":
        return ()
    try:
        parsed = ast.literal_eval(value)
    except (SyntaxError, ValueError):
        parsed = [part.strip().strip('"\'') for part in value.strip("[]").split(",")]
    if not isinstance(parsed, list) or not all(isinstance(tag, str) and tag for tag in parsed):
        raise ValueError(f"invalid Raindrop tag list: {value}")
    return tuple(parsed)


def normalise_url(url: str) -> str:
    parts = urlsplit(url.strip().strip('"'))
    return urlunsplit((parts.scheme.lower(), parts.netloc.lower(), parts.path.rstrip("/"), parts.query, ""))


def iso_week(day: str) -> str:
    value = date.fromisoformat(day)
    year, week, _ = value.isocalendar()
    return f"{year:04d}-W{week:02d}"


def monday(week: str) -> date:
    year, number = week.split("-W")
    return date.fromisocalendar(int(year), int(number), 1)


def escape_title(title: str, url: str) -> str:
    """Use character references where source punctuation would close markup."""

    text = title or url
    for character, entity in (
        ("&", "&amp;"), ("\\", "&#92;"), ("{", "&#123;"), ("}", "&#125;"),
        ("[", "&#91;"), ("]", "&#93;"), ("(", "&#40;"), (")", "&#41;"),
        ('"', "&quot;"), ("%", "&#37;"),
    ):
        text = text.replace(character, entity)
    return text


def load_links(cog_land: Path) -> list[Link]:
    root = cog_land / "clips" / "raindrops"
    links: list[Link] = []
    empty_seen: set[str] = set()
    for path in sorted(root.rglob("*.md")):
        metadata = frontmatter(path)
        source_date = metadata.get("date", "")[:10]
        url = metadata.get("url", "").strip().strip('"')
        if not (source_date > AFTER and url):
            continue
        relative = str(path.relative_to(root))
        tags = parse_tags(metadata.get("tags", "[]"))
        if not tags:
            empty_seen.add(relative)
            tags = EMPTY_TAGS.get(relative, ())
        # This stale-bot clip is deliberately retained in the source audit so
        # that the baseline URL check can exclude it.  It is never rendered.
        if not tags and relative != "learning-diary/2025-10-10-github-stale-bot-considered-harmful.md":
            raise ValueError(f"empty tag review is missing for {relative}")
        links.append(Link(relative, url, metadata.get("title", "").strip().strip('"'), source_date, tags))
    if len(links) != EXPECTED_SOURCE or empty_seen != (set(EMPTY_TAGS) | {"learning-diary/2025-10-10-github-stale-bot-considered-harmful.md"}):
        raise ValueError("Raindrop source set or empty-tag review changed; review before importing")
    return links


def forest_urls() -> set[str]:
    urls: set[str] = set()
    for path in TREES_DIR.glob("*.tree"):
        text = path.read_text(encoding="utf-8")
        # Ignore only this script's previous output on reruns.  Existing weekly
        # trees, including the pre-existing W41 stale-bot entry, stay in the
        # deduplication baseline.
        if GENERATED_MARKER in text.splitlines()[:3]:
            continue
        for raw in re.findall(r'https?://[^\s)\]}"<>]+', text):
            urls.add(normalise_url(raw.rstrip(".,;:")))
    return urls


def allocate(links: list[Link]) -> dict[str, list[Link]]:
    """Merge sparse adjacent receipts; spread dense week batches to 10–15 links."""

    by_week: dict[str, list[Link]] = defaultdict(list)
    for link in links:
        by_week[iso_week(link.source_date)].append(link)
    output: dict[str, list[Link]] = defaultdict(list)
    for week, batch in sorted(by_week.items()):
        chunks = (len(batch) + MAX_DAILY - 1) // MAX_DAILY
        base, remainder = divmod(len(batch), chunks)
        source_days = sorted({date.fromisoformat(link.source_date) for link in batch})
        if chunks == 1:
            targets = [source_days[-1]]
        elif chunks <= len(source_days):
            targets = source_days[-chunks:]
        else:
            # Stay in the receipt's ISO week.  This avoids accidentally
            # combining an added Sunday with the prior week's last-day node.
            week_start = monday(week)
            candidates = [week_start + timedelta(days=offset) for offset in range(7) if week_start + timedelta(days=offset) not in source_days]
            candidates.sort(key=lambda day: (min(abs((day - source).days) for source in source_days), -day.toordinal()))
            targets = sorted(source_days + candidates[: chunks - len(source_days)])
        ordered = sorted(batch, key=lambda link: (link.tags, normalise_url(link.url)))
        cursor = 0
        for index, target in enumerate(targets):
            size = base + (1 if index < remainder else 0)
            output[target.isoformat()].extend(ordered[cursor : cursor + size])
            cursor += size
    counts = [len(items) for items in output.values()]
    if sum(counts) != EXPECTED_OUTPUT or max(counts) > MAX_DAILY:
        raise ValueError("allocation no longer meets the Raindrop count/cap invariants")
    return dict(sorted(output.items()))


def tag_tree(links: list[Link]) -> dict[str, object]:
    root: dict[str, object] = {"children": {}, "links": []}
    for link in sorted(links, key=lambda item: (item.tags, normalise_url(item.url))):
        node = root
        for raw_tag in link.tags:
            # Raindrop's slash-bearing labels are atomic tags, not a hierarchy.
            children = node["children"]
            assert isinstance(children, dict)
            node = children.setdefault(raw_tag, {"children": {}, "links": []})
        leaves = node["links"]
        assert isinstance(leaves, list)
        leaves.append(link)
    return root


def render_tag_tree(node: dict[str, object], depth: int) -> list[str]:
    lines: list[str] = []
    children = node["children"]
    assert isinstance(children, dict)
    for tag in sorted(children):
        lines.append(f"{'    ' * depth}- #{tag}")
        child = children[tag]
        assert isinstance(child, dict)
        lines.extend(render_tag_tree(child, depth + 1))
    leaves = node["links"]
    assert isinstance(leaves, list)
    for link in leaves:
        assert isinstance(link, Link)
        lines.append(f"{'    ' * depth}- [{escape_title(link.title, link.url)}]({link.url})")
    return lines


def weekly_tree(week: str, days: dict[str, list[Link]]) -> str:
    entries = []
    for day, links in sorted(days.items()):
        body = "\n".join(render_tag_tree(tag_tree(links), 0))
        entries.append(f"\\subtree[{day}]{{\\mdnote{{{day}}}{{\n{body}\n}}}}")
    return (
        "\\import{macros}\n"
        + GENERATED_MARKER + "\n\n"
        f"\\title{{{week}}}\n"
        f"\\date{{{monday(week).isoformat()}}}\n\n"
        "\\scope{\n  \\put\\transclude/toc{false}\n  \\put\\transclude/expanded{false}\n"
        f"  \\subtree[{week}-links]{{\n\\title{{🔗}}\n\n"
        "    \\scope{\n      \\put\\transclude/expanded{true}\n"
        + "\n\n".join(entries) + "\n    }\n  }\n}\n"
    )


def root_sections(weeks: list[str], first_days: dict[str, str]) -> tuple[str, str]:
    years: dict[int, dict[str, list[str]]] = defaultdict(lambda: defaultdict(list))
    for week in weeks:
        day = date.fromisoformat(first_days[week])
        years[day.year][day.strftime("%Y-%m")].append(week)
    def months(year: int) -> str:
        lines: list[str] = []
        for month, names in sorted(years[year].items(), reverse=True):
            lines.extend([f"\\subtree[{month}]{{", f"\\title{{{date.fromisoformat(month + '-01').strftime('%B, %Y')}}}", ""])
            for week in sorted(names, reverse=True):
                lines.extend([f"% Raindrop link intake: {week}", f"\\transclude{{{week}}}", ""])
            lines.extend(["}", ""])
        return "\n".join(lines)
    return (months(2025), "\\subtree[2026]{\n\\title{Year 2026}\n\n" + months(2026) + "}\n\n")


def expected_root(root: str, year_2025: str, year_2026: str) -> str:
    start_2025 = root.index(ROOT_2025)
    # The generated 2025 October section precedes the original live October
    # section.  The latter is the final occurrence and must remain untouched.
    baseline_2025 = root.rindex(ROOT_2025_BASELINE_MONTH)
    # A generated 2026 block is inserted before the live 2025 section.  Strip
    # it on re-planning so the import remains byte-idempotent.
    generated_2026 = root.find("\\subtree[2026]{", 0, start_2025)
    prefix = root[:generated_2026 if generated_2026 >= 0 else start_2025]
    suffix = root[baseline_2025:]
    return prefix + year_2026 + ROOT_2025 + ROOT_2025_TITLE + year_2025 + suffix


def plan(cog_land: Path) -> tuple[dict[Path, str], str, dict[str, list[Link]]]:
    source = load_links(cog_land)
    baseline = forest_urls()
    links = [link for link in source if normalise_url(link.url) not in baseline]
    if len(source) - len(links) != EXPECTED_BASELINE_EXCLUSIONS or len(links) != EXPECTED_OUTPUT:
        raise ValueError("Raindrop baseline deduplication changed; review before importing")
    allocated = allocate(links)
    by_week: dict[str, dict[str, list[Link]]] = defaultdict(lambda: defaultdict(list))
    for day, links_for_day in allocated.items():
        by_week[iso_week(day)][day].extend(links_for_day)
    trees = {TREES_DIR / f"{week}.tree": weekly_tree(week, days) for week, days in by_week.items()}
    first_days = {week: min(days) for week, days in by_week.items()}
    year_2025, year_2026 = root_sections(sorted(by_week), first_days)
    return trees, (year_2025, year_2026), allocated


def distribution(allocated: dict[str, list[Link]]) -> str:
    weeks: dict[str, list[str]] = defaultdict(list)
    for day, links in allocated.items():
        weeks[iso_week(day)].append(f"{day}: {len(links)}")
    return "\n".join(f"{week} — " + "; ".join(days) for week, days in sorted(weeks.items()))


def owned(path: Path, week: str) -> bool:
    text = path.read_text(encoding="utf-8")
    return (
        text.startswith("\\import{macros}\n" + GENERATED_MARKER + "\n\n" + f"\\title{{{week}}}\n")
        and f"\\subtree[{week}-links]{{" in text
        and "\\title{🔗}" in text
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cog-land", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--distribution", action="store_true", help="print the date-level plan without writing")
    parser.add_argument("--refresh", action="store_true", help="replace only a prior generated target")
    args = parser.parse_args()
    root = ROOT_TREE.read_text(encoding="utf-8")
    trees, (year_2025, year_2026), allocated = plan(args.cog_land.expanduser().resolve())
    title_arrangement = ROOT_2025_TITLE in root or (ROOT_2025 + ROOT_2025_TITLE.lstrip("\n")) in root
    if ROOT_2025 not in root or not title_arrangement or ROOT_2025_BASELINE_MONTH not in root:
        raise ValueError("live diary root no longer has the expected 2025 arrangement")
    expected = expected_root(root, year_2025, year_2026)
    stale = [path for path, content in trees.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]
    if args.distribution:
        print(distribution(allocated))
    if args.check and (stale or root != expected):
        raise ValueError("--check found a non-current Raindrop import")
    if not args.check and not args.distribution:
        if root != expected and "\\subtree[2026]{" in root and "% Raindrop link intake:" not in root:
            raise ValueError("refusing to overwrite a non-generated 2026 root arrangement")
        for path, content in trees.items():
            if path.exists() and path.read_text(encoding="utf-8") != content and not (args.refresh and owned(path, path.stem)):
                raise ValueError(f"refusing to overwrite a non-current weekly tree: {path}")
        for path, content in trees.items():
            path.write_text(content, encoding="utf-8")
        ROOT_TREE.write_text(expected, encoding="utf-8")
    print(f"{'validated' if args.check else 'planned' if args.distribution else 'imported'} {EXPECTED_OUTPUT} Raindrop links into {len(trees)} weekly trees and {len(allocated)} dates")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
