
[tasks.build]
description = "Meta build: all atomic build steps"
depends = ["bun_js", "bun_css", "wasm", "forest", "xml_to_html", "assets"]

# Keep the original just build as a fallback

# Keep the original just build as a fallback
[tasks.just_build]
description = "Legacy: just build"
run = '''
#!/usr/bin/env bash
echo "RUNNING: just_build"
just build
'''

