[tasks.build]
description = "Meta build: all atomic build steps"
depends = ["build:bun_js", "build:bun_css", "build:wasm", "build:forest", "build:xml_to_html", "build:assets"]

# Keep the original just build as a fallback
[tasks.just_build]
description = "Legacy: just build"
run = '''
#!/usr/bin/env bash
echo "RUNNING: just_build"
just build
'''

[tasks."build:check"]
description = "Check build output parity between just and mise"
run = '''
#!/usr/bin/env bash
uv run check_build_parity.py
'''

