# credits
# - https://felix-knorr.net/posts/2025-03-16-helix-review.html
# - https://github.com/TimothyYe/mydotfiles/blob/51160e906cf9c1192bc75ea8f76e92f628f097d6/helix/config.toml#L19
# - https://github.com/kristijanhusak/neovim-config/blob/2e1b956910ed635d60631940b3fdd6782352b601/helix/config.toml#L4
# - https://github.com/mimame/.dotfiles/blob/81d1c6caa6d28ed223d54b3067311743300b8f6d/helix/config.toml#L10

# ret means enter

# :config-reload or just ret+r to apply changes
# theme = "onedark"
# theme = "github_dark"
# theme = "tokyonight_moon"
# theme = "catppuccin_mocha"
# theme = "base16_default_dark"
# theme = "material_darker"
# theme = "term16_dark" # image background
# theme = "base16-railscasts"
# theme = "alevia-dark"
theme = "alevia-railscasts"

[editor.file-picker]
hidden = false

[editor]
line-number = "relative"
# mouse = false
color-modes = true
# auto-completion = true
bufferline = "multiple"
cursorline = true

[editor.auto-save]
# focus-lost = true
#

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
# Remove auto-pairing for `, as it's not friendly to ```
# '`' = '`'
'<' = '>'

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

[editor.statusline]
left = ["mode", "spacer", "version-control", "file-name", "file-modification-indicator", "register"]
right = ["diagnostics", "spacer", "spinner", "spacer", "file-type", "separator", "position", "separator", "spacer", "position-percentage"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
# Display LSP progress messages below statusline
display-messages = true
# Display inlay hints
display-inlay-hints = true
# Display LSP progress messages below statusline
display-progress-messages = true

[editor.whitespace]
# Whether to render whitespace
render = "none"

[editor.whitespace.characters]
# Literal characters to use when rendering whitespace
# Sub-keys may be any of
# Options for rendering whitespace with visible characters.
# Use `:set whitespace.render all` to temporarily enable visible whitespace.
# Use `:set whitespace.render none` to disable again
# Or, simply use ret+v to toggle
space = "·"
nbsp = "⍽"
tab = "→"
newline = "↩" # ↵ ⏎ ↩

[editor.soft-wrap]
enable = true

# Keep all my personal keymap under ret
[keys.normal.ret]

# reload config and lsp
r = [":config-reload", ":reload-all", ":lsp-restart"]

# close window
q = ":q"

# close tab
c = ":buffer-close"
C = ":buffer-close!"

# prev/next tab
"[" = "goto_previous_buffer"
"]" = "goto_next_buffer"

# save file
ret = ":w"
w = ":w"

# toggle whitespace render
v = ":toggle-option whitespace.render all none"

# Really escape - no more fighting with the cursor or with multiple cursors
# esc = ;,esc
# Not working as it only stops the key seqence
# esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

# set lang
m = ":lang markdown"

# open log
l = ":log-open"

# Open TUIs

# scooter - search & replace in workspace - ctrl-c to quit
"/" = [
    ":write-all",
    ":new",
    ":insert-output scooter > /dev/tty",
    ":set mouse false",
    ":set mouse true",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
# lazygit - q to quit
g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":set mouse false",
    ":set mouse true",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]

# jjui
j = [
    ":write-all",
    ":new",
    ":insert-output jjui >/dev/tty",
    ":set mouse false",
    ":set mouse true",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]

# yazi
# https://www.reddit.com/r/HelixEditor/comments/1kwk74i/trying_to_use_yazi_inside_of_helix/
# https://github.com/sxyazi/yazi/pull/2461
# requires helix HEAD and latest yazi
y = [
    ':sh rm -f /tmp/yazi-uniq-file',
    ':insert-output yazi %{buffer_name} --chooser-file=/tmp/yazi-uniq-file',
    ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
    ':open %sh{cat /tmp/yazi-uniq-file}',
    ":set mouse false",
    ":set mouse true",
    ':redraw',
]
