# based on https://github.com/helix-editor/helix/issues/5365
[[language]]
name = "forester"
scope = "source.tree"
injection-regex = "forester"
file-types = ["tree"]
roots = [ "forest.toml" ]
comment-tokens = "%"
indent = { tab-width = 2, unit = "  " }
grammar = "forester"

# https://writewithharper.com/docs/integrations/helix#Optional-Configuration
[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
config = { harper-ls = { diagnosticSeverity = "error", linters = { long_sentences = false } } }

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]

[[language]]
name = "forester"
language-servers = ["harper-ls"]

# Not working: panicked
# # based on https://iwe.md/quick-start/
# [language-server.iwe]
# command = "iwes"

# [[language]]
# name = "markdown"
# language-servers = [ "iwe" ] # you might want more LSPs in here
# # auto-format = true # optional, enable format-on-save

# [language-server.llmvm-codeassist-rust]
# command = "llmvm-codeassist"
# args = ["rust-analyzer"]

# [[language]]
# name = "rust"
# language-servers = [ "llmvm-codeassist-rust" ]

