# based on https://github.com/helix-editor/helix/issues/5365
[[language]]
name = "forester"
scope = "source.tree"
injection-regex = "forester"
file-types = ["tree"]
roots = [ "forest.toml" ]
comment-tokens = "%"
indent = { tab-width = 2, unit = "  " }
grammar = "forester"
