# https://dystroy.org/broot/conf_file/

# https://github.com/Canop/broot/issues/971#issuecomment-2676758735
kitty_graphics_transmission = "chunks"

syntax_theme = "MochaDark"

# show git status and hidden files
default_flags = "-gh"

[[verbs]]
invocation = "edit"
key = "enter"
shortcut = "e"
execution = "hx {file}"
apply_to = "text_file"
leave_broot = false
