# Theme name: Alevia Dark
# A remix of Vibrant Ink and All Hellow's Eve
# I created it back in the days working with Java in Eclipse
# See https://utensil.github.io/tech/2009/08/11/comfort-eclipse.html for more background
#
# Color scheme documentation:
# - Comments:         #C6ABD8 (light purple)
# - Numbers:         #00F0F0 (bright cyan)
# - Methods:         #F7C527 (golden yellow)
# - Keywords:        #CC7833 (burnt orange)
# - Operators:       #EC6C1E (orange-red)
# - Strings:         #477488 (steel blue)
# - Classes:         #9CF828 (lime green)
# - Local vars:      #3C758D (deep sky blue)
# - Parameters:      #4B9CE9 (bright blue)
# - Fields:          #357A8F (ocean blue)
# - Headings:        #6D9CBE (soft blue)
# - Bold text:       #FFC66D (light gold)
# - Italic text:     #B6B3EB (lavender)
# - Links:           #CC7833 (burnt orange)
# - Quotes:          #519F50 (leaf green)
# - Raw text:        #A5C261 (pea green)
# - Background:      #191919 (near black)
# - Cursor:          #FFC66D (light gold)
# - Line numbers:    #F9F9F9 (bright white)
# - Selection:       #414C3B (dark olive)
# - Statusline:      #FFFFFF (white) on #272935 (dark slate)
# - Text:            #FFFFFF (white)
# - Indent guides:   #5A647E (slate blue)
# - Diff added:      #A5C261 (pea green)
# - Diff removed:    #DA4939 (vermillion red)
# - Diff changed:    #CC7833 (burnt orange)

"comment" = { fg = "#C6ABD8", modifiers = ["italic"] }       # Light purple italic comments
"constant" = "#CC7833"                                       # Orange constants/booleans
"constant.numeric" = "#00F0F0"                               # Bright cyan numbers
"constructor" = "#F7C527"                                    # Golden yellow methods
"function" = "#F7C527"                                       # Golden yellow functions
"keyword" = "#CC7833"                                        # Orange keywords
"operator" = "#EC6C1E"                                       # Orange-red operators
"string" = "#A5C261"                                        # Green strings
"type" = "#9CF828"                                           # Lime green classes
"variable" = "#3C758D"                                       # Deep sky blue local vars
"variable.parameter" = "#4B9CE9"                             # Bright blue parameters
"variable.other.member" = "#357A8F"                           # Ocean blue fields

"markup.heading" = "#6D9CBE"                                  # Soft blue headings
"markup.bold" = { fg = "#FFC66D", modifiers = ["bold"] }     # Light gold bold text
"markup.italic" = { fg = "#B6B3EB", modifiers = ["italic"] }  # Lavender italic text
"markup.link.url" = { fg = "#CC7833", modifiers = ["underlined"] } # Orange underlined links
"markup.quote" = "#519F50"                                   # Leaf green quotes
"markup.raw" = "#477488"                                    # Steel blue raw text

"ui.background" = {}  # transparent # { bg = "#191919" }    # Near black background
"ui.cursor" = { fg = "#FFC66D", modifiers = ["reversed"] }    # Gold reversed cursor
"ui.linenr" = { fg = "#B0B0B0", bg = "#191919" }             # Further dimmed line numbers
"ui.selection" = { bg = "#414C3B" }                          # Dark olive selection
"ui.statusline" = { fg = "#B0B0B0", bg = "#272935" }         # Further dimmed status text
"ui.text" = "#D0D0D0"                                        # More dimmed main text
"ui.virtual.indent-guide" = { fg = "#5A647E" }               # Slate blue indent guides

"diagnostic.error" = { underline = { style = "curl" } }       # Error underlines
"diagnostic.warning" = { underline = { style = "curl" } }    # Warning underlines
"diagnostic.info" = { underline = { style = "curl" } }       # Info underlines
"diagnostic.hint" = { underline = { style = "curl" } }       # Hint underlines

"diff.plus" = "#A5C261"                                      # Pea green additions
"diff.minus" = "#DA4939"                                     # Vermillion deletions
"diff.delta" = "#CC7833"                                     # Orange changes
