services:
  knot:
    image: hqnna/knot:v1.6.0-alpha
    container_name: knot
    restart: unless-stopped
    ports:
      - "5555:5555"  # Knot service
      - "5522:22"    # Expose SSH
    volumes:
      - ${PODS_HOME}/knot/keys:/etc/ssh/keys
      - ${PODS_HOME}/knot/repositories:/home/git/repositories
      - ${PODS_HOME}/knot/data:/app
    environment:
      - KNOT_SERVER_HOSTNAME=${KNOT_SERVER_HOSTNAME}
      - KNOT_SERVER_SECRET=${KNOT_SERVER_SECRET}
      - KNOT_SERVER_PORT=80
      - KNOT_SERVER_DB_PATH=/app/knotserver.db
      - KNOT_REPO_SCAN_PATH=/home/git/repositories
      - KNOT_SERVER_INTERNAL_LISTEN_ADDR=127.0.0.1:5444
      - KNOT_SERVER_LISTEN_ADDR=0.0.0.0:5555
      - APPVIEW_ENDPOINT=https://tangled.sh
    # network_mode: bridge
