services:
    ubuntu:
        container_name: ubuntu_pro
        stdin_open: true
        tty: true
        # privileged: true
        image: ubuntu:22.04
        platform: linux/amd64
        command: bash
        working_dir: /root/projects/forest
        volumes:
            - $PROJECTS/forest:/root/projects/forest
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
networks: {}
