[buffer]
# styling = false

# scripting = true
# "app" also enables JavaScript APIs that can be used to fingerprint users (e.g. querying the window’s size.)
scripting = "app"

images = true

# reads cookies, but does not modify it
# cookie = true
# cookies are also saved to external.cookie-file
cookie = "save"

# referer-from = true
# history = false

[input]
# use-mouse = false

[display]
# color-mode = "monochrome" # -M from CLI
color-mode	= "true-color"
# image-mode = "kitty"

[external]
copy-cmd = "pbcopy" # macos
editor = "exec hx +%d"

[page]
' r' = "pager.externFilterSource('rdrview -Hu \"$CHA_URL\" --disable-sandbox')"

# don't need these now, just get used to ,. (<> without shift)
# "C-o" = "cmd.pager.prevBuffer"
# "C-i" = "cmd.pager.nextBuffer" # doesn't work
